name: Get some package changed in workspaces
description: A github action that gets changed workspaces
author: Aleksandras Sukelovic <alex.shukel@gmail.com>
inputs:
    workspaces:
        description: Paths where to get changed workspaces
        required: false
    working-directory:
        description: Path to the directory that contains root package.json of monorepo
        required: false
    filter:
        description: Regex pattern to filter changed packages by name
        required: false
    base-ref:
        description: |
            Git base reference (branch name or a commit hash). The change list will be compared to the base if
            push event occurs. Will default to the last commit of the current branch
        required: false
        default: ${{ github.ref }}
    changed-files:
        description: Array of changed files
        required: true
outputs:
    packages:
        description: Array of changed packages, each containing its name and path
    empty:
        description: Boolean that indicates if there was any changed packages

runs:
    using: node16
    main: dist/index.js

branding:
    icon: package
    color: blue
