name: Build

on:
    push:
        paths:
            - "src/**"
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.18
              uses: actions/setup-node@v4
              with:
                node-version: '20.18'
                cache: 'npm'

            - name: Installing dependencies
              run: npm install

            - name: Building
              run: npm run build

            - name: Committing & pushing
              run: |
                  git config --global user.name 'sologeek'
                  git config --global user.email 'sologeek@users.noreply.github.com'
                  git commit -am "Build $(date +'%F %T')"
                  git push origin main
